// 二组/刘洋/2.11/react-app/src/views/login/login.js
import React, { Component } from 'react'
import httpAxios from '../../utils/request'
export default class login extends Component {
    constructor(){
        super()
        this.state={
            name:"",
            pwd:""
        }
    }
    changeVal(e){
        let name=e.target.name
        this.setState({
            [name]:e.target.value
        })
        
    }
   async login(){
        let {name,pwd}=this.state
       let res=await httpAxios.post("/api/login",{name,pwd})
       console.log(res.data)
       if(res.data.code===1){
           console.log(this.props.history)
           localStorage.name=res.data.data.name
           localStorage.token=res.data.data.token
           localStorage.statu=res.data.data.statu
           this.props.history.push("/index")
       }else{
           alert(res.data.msg)
       }
    }
    toregister(){
        this.props.history.push("/register")
    }
    render() {
        let {name,pwd}=this.state
        return (
            <div className="login">
               <p>用户名:<input value={name} name="name" onChange={(e)=>{this.changeVal(e)}}></input></p>
               <p>密码:<input value={pwd} name="pwd"  onChange={(e)=>{this.changeVal(e)}}></input></p>
               <button onClick={()=>{this.login()}}>登陆</button>
               <button onClick={()=>{this.toregister()}}>注册</button>
            </div>
        )
    }
}

// 六组/张卓/2_6作业/vue/src/views/login.vue
<!-- login -->
<template>
    <div>
       <el-form ref="form" :model="form" label-width="80px">
      <el-form-item label="用户名">
        <el-input v-model="form.name"></el-input>
      </el-form-item>
       <el-form-item label="密码">
        <el-input v-model="form.pwd"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="logIn">登录</el-button>
        <p :class="{'active':isShow}" @click="registry">注册</p>
      </el-form-item>
    </el-form>
    </div>
</template>

<script>
import httpAxios from './../utils/requset.js'

export default {
  components: {},
  data () {
    return {
      form:{
          name:"",
          pwd:""
      },
      isShow:false 
    };
  }, 
  computed: {}, 
 // mounted: {},

  methods: {
   async logIn(){     
       const {name,pwd} = this.form       
          //  console.log(555,name);
       let res = await  httpAxios.post('/api/login',{name,pwd})
       console.log(res);
       if(res.data.code==1){
         console.log(res.data,'登录成功');
         localStorage.setItem("token", res.data.token);
         localStorage.setItem("name", name);
         this.$router.push("/home")
       }else{
          console.log(res.data.mes)
          alert(res.data.mes)
          this.isShow = true
       } 
    },
    registry() {
      this.$router.push("/registry");
    }
  }
}

</script>
<style lang='scss' scoped>

</style>
