// 六组/郭勇良/2.12作业/qx-react/src/views/Registry/Registry.js
import React, { Component } from 'react'
import axios from "axios"
export default class Login extends Component {
    state = {
        name: '',
        pwd: ''
    }
    render() {
        let { name, pwd } = this.state;
        return (
            <div className="registry">
                <p>
                    <input placeholder="请输入用户名" value={name} name="name" onChange={this.handleChange.bind(this)} />
                </p>
                <p>
                    <input type="password" placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handleChange.bind(this)} />
                </p>

                <button onClick={this.handleSubmit.bind(this)}>注册</button>
            </div>
        )
    }
    handleChange(e) {
        let name = e.target.name;
        this.setState({
            [name]: e.target.value
        })
    }
    async handleSubmit() {
        let { name, pwd } = this.state;
        let res = await axios.post('/registry', {
            name, pwd
        });
        if (res.data.code == 1) {
            this.props.history.go(-1)
        } else if (res.data.code == 3) {
            this.props.history.push("/registry")
        }
    }

}

// 七组/赵春荣/2.4作业/语雀前端/src/views/registry/registry.vue
<template>
  <div class='registry'>
     <el-input v-model="name" placeholder="请输入内容" class="input"></el-input>
    <br/>
    <el-input placeholder="请输入密码" v-model="pwd" show-password class="input"></el-input>
     <el-button type="primary" @click='fn'>注册</el-button> 
  </div>
</template>
<script>
import axios from "axios"
import {registry} from "../../api/api"
export default {
  data(){
    return{
      name:'',
      pwd:''
    }
  },
  methods: {
    fn(){
      const {name,pwd}=this;
    registry({
     name,pwd
     }).then(res=>{
       console.log(res.data)
       if(res.data.code===1){
         alert('注册成功')
         this.$router.push('/login')
       }
     })
    }
  },
}
</script>
<style>
  .registry{

    width:100%;
    height:300px;
    border:1px solid #ccc;
    margin:60 auto;
  }
  .registry .input{
   margin:20px;
  }

</style>
