// 五组/陈冠廷/2-5作业/qian/src/views/registry/registry.vue
<template>
  <div class="registry">
      <div class="registry-box">
        <p><input placeholder="名字" v-model="name"></p>
        <p><input placeholder="密码" v-model="pwd"></p>
        <p><el-button :plain="true" @click="registry">注册</el-button></p>
      </div>
  </div>
</template>

<script>
import httpAxios from '../../utils/request';
export default {
 data(){
   return {
     name:'',
     pwd:''
   }
 },
 methods:{
  async registry(){
     let {name,pwd}=this;
     console.log(name,pwd)
    if(!name||!pwd){
      this.$message('缺少参数');
      return;
    }
    let res=await httpAxios.post('/api/registry',{name,pwd});
    // console.log(res)
    if(res.data.code==1){
      this.$router.push('/login');
    }else{
       this.$message('注册失败');
    }
   }
 }
}
</script>

<style>

</style>

// 七组/崔学敏/2.14作业/react-demo/src/views/Registry.js
import React, { Component } from 'react'
import httpAxios from '../utils/request.js'

export default class Registry extends Component {
    state = {
        phone: '',
        pwd: ''
    }
  render() {
    let { phone, pwd } = this.state;

    return (
      <div className="registry">
        <div className="cont">
                    <input type="text" placeholder="请输入手机号" value={phone} name='phone' onChange={this.handleChange.bind(this)} /><br />
                    <input type="text" placeholder="请输入密码" value={pwd} name='pwd' onChange={this.handleChange.bind(this)} /><br />
                   
                    <button onClick={this.handleZc.bind(this)}>注册</button><br/>
                    <button onClick={this.goToLogin.bind(this)}>去登录</button>
                    
                </div>
      </div>
    )
  }
  handleChange(e) {
    let name = e.target.name;
    this.setState({
        [name]: e.target.value
    })
}
async handleZc(){
    let { phone, pwd } = this.state;
let res=await httpAxios.post('/registry',{phone,pwd});
if(res.data.code==1){
    alert(res.data.mes)
}else{
  alert(res.data.mes)
}
}
goToLogin(){
    this.props.history.push('/deng')
}
}
