// 一组/杨卓/2月10日作业/ConferenceRoom-前台/src/views/login/login.vue
<template>
  <div class="login-page">
    <div class="login-main">
      <h1>会议室预定系统</h1>
      <div>
        <span class="icon iconfont icon-yonghu"></span>
        <input type="text" placeholder="用户名" v-model="name" />
      </div>
      <div>
        <span class="icon iconfont icon-mima"></span>
        <input type="text" placeholder="密码" v-model="pwd" />
      </div>
      <div>
        <button @click="loginfn">登录</button>
      </div>
      <div v-if="flag">
        去
        <button class="regclass" @click="$router.push('/register')">注册</button>
      </div>
    </div>
  </div>
</template>

<script>
import "@/font/iconfont.css"; //引入图标样式
import axios from "axios";
export default {
  data() {
    return {
      name: "",
      pwd: "",
      flag: false
    };
  },
  methods: {
    async loginfn() {//登录
      let { name, pwd } = this;
      let res = await axios.post("/api/login", { name, pwd });
      if (res.data.code == 4) {//缺少参数
        this.$message({
          message: res.data.msg,
          center: true,
          duration: "1000" 
        });
        return;
      }
      if (res.code == 3) {//类型校验失败
        this.$message({
          message: res.data.msg,
          center: true,
          duration: "1000" 
        });
        return;
      }
      if(res.data.code==2){//没有该用户
        this.flag=true
      }
      console.log(res, "EEEEEEE");
      if (res.data.code == 1) {
        //登录成功
        window.Location.user = JSON.stringify(res.data);
        this.$router.push("/home");
        this.$message({
          message: res.data.msg,
          center: true,
          duration: "1000" //设置时间
        });
      } else {
        this.$message({
          message: res.data.msg,
          center: true,
          duration: "1000"
        });
      }
    }
  }
};
</script>

<style>
.login-main > div > .regclass {
  width: 40px;
  background: #fff;
  color: red;
  font-size: 18px;
  cursor: pointer;
}
.login-main > div > button {
  margin: 0 10px;
  border: 0;
  outline: 0;
  background: rgb(244, 243, 243);
  width: 300px;
  height: 30px;
}
.login-main > div > span {
  margin-right: 20px;
}
.login-main > div {
  line-height: 80px;
}
.login-main {
  width: 600px;
  height: 500px;
  margin: auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.login-page {
  width: 100%;
  height: 100%;
}
</style>

// 一组/杨卓/2月14日作业/mevos-react-前端/src/view/Login/Login.js
import React, { Component } from 'react'
import axios from 'axios'
import "antd-mobile/lib/toast/style/css"
import Toast from "antd-mobile/lib/toast"
export default class Login extends Component {
    state={
        phone:"",
        pwd:"",
        // flag:false
    }
    render() {
        let {phone,pwd}=this.state
        return (
            <div className='login-page'>
                <div className="login-main">
                <h1>美沃斯数据管理中心</h1>
                <div className='login-main-main'>
                    <div>
                        <input type="text" placeholder="手机号" value={phone} name='phone' onChange={this.handleChange.bind(this)}/>
                    </div>
                    <div>
                        <input type="text" placeholder="密码" value={pwd} name='pwd' onChange={this.handleChange.bind(this)} />
                    </div>
                    <div>
                        <button onClick={()=>{this.loginfn()}}>登录</button>
                    </div>
                </div>
                </div>
            </div>
        )
    }
    handleChange(e){
        let name=e.target.name;
        this.setState({
            [name]:e.target.value
        })        
    }
    loginfn=()=>{
        let phone=this.state.phone
        let pwd=this.state.pwd
        axios.post("/login",{phone,pwd}).then((res)=>{
            console.log(res.data.code);
            if(res.data.code===4){//缺少参数
                Toast.info(res.data.msg)
                return;
            }
            if(res.data.code===3){//参数校验失败
                Toast.info(res.data.msg)
                return;
            }
            if(res.data.code===2){//没有该用户
                Toast.info(res.data.msg)
                this.props.history.push({pathname:"/register"})
                return;
            }
            if(res.data.code===1){//登录成功
                window.localStorage.user=JSON.stringify(res.data)
                this.props.history.push({pathname:"/home"})
                Toast.info(res.data.msg)
            }else{//登录失败
                Toast.info(res.data.msg)
            }
        })
    }
}
