// 五组/陈冠廷/2-5作业/qian/src/views/registry/registry.vue
<template>
  <div class="registry">
      <div class="registry-box">
        <p><input placeholder="名字" v-model="name"></p>
        <p><input placeholder="密码" v-model="pwd"></p>
        <p><el-button :plain="true" @click="registry">注册</el-button></p>
      </div>
  </div>
</template>

<script>
import httpAxios from '../../utils/request';
export default {
 data(){
   return {
     name:'',
     pwd:''
   }
 },
 methods:{
  async registry(){
     let {name,pwd}=this;
     console.log(name,pwd)
    if(!name||!pwd){
      this.$message('缺少参数');
      return;
    }
    let res=await httpAxios.post('/api/registry',{name,pwd});
    // console.log(res)
    if(res.data.code==1){
      this.$router.push('/login');
    }else{
       this.$message('注册失败');
    }
   }
 }
}
</script>

<style>

</style>

// 六组/韩丞星12/2.12/src/registry/registry.jsx
import React, { Component } from 'react'
import axios from "axios"
export default class Registry extends Component {
    state={
        name:"",
        pwd:""
    }
    changevalue(e){
        let key=e.target.name
        this.setState({
            [key]:e.target.value
        })
    }
    async registry(){
        let {name,pwd}=this.state
        let res=await axios.post('/registry',{name,pwd})
        console.log(res)
        if(res.data.code===1){
            this.props.history.go(-1)
        }else{
            console.log("注册失败")
        }
    }
    render() {
        let {name,pwd}=this.state
        return (
            <div>
                <p>账号: <input type="text" value={name} name="name" onChange={this.changevalue.bind(this)} /></p>
                <p>密码: <input type="text" value={pwd} name="pwd" onChange={this.changevalue.bind(this)} /></p>
                <button onClick={this.registry.bind(this)}>注册</button>
            </div>
        )
    }
}
