// 三组/刘枭飞/2.3router/src/views/Login/Login.vue
<template>
  <div>
    <el-input v-model="name" placeholder="请输入名字"></el-input>
    <el-input placeholder="请输入密码" v-model="pwd" show-password></el-input>
 <el-button type="primary" @click="dl">登陆</el-button>
   <a href="/zc">注册</a>
  </div>
</template>

<script>

import axios from "../../utils/httpAxios"
export default {
  data() {
    return {
      name:"",
      pwd:""
    }
  },
  methods:{
   async dl(){
     let {name,pwd} = this
     let res = await axios.post("/api/login",{name,pwd})
     console.log(res)
     if(res.data.code==1){
        window.localStorage.token = res.data.token;
        window.localStorage.uid = res.data.uid;
       this.$router.push("/home")
     }else{
       alert(res.data.msg)
     }
    }
  }
}
</script>

<style>

</style>

// 三组/叶子文/2.13作业/react-2.12/src/views/Login/Login.js
import React, { Component } from 'react'
import { Input, Button } from 'antd'
import axios from 'axios'

export default class Login extends Component {
  state = {
    tel: "",
    pwd: "",
    flag: false
  }
  render() {
    let { tel, pwd, flag } = this.state;
    return (
      <div className="login">
        <div className="form">
          <Input placeholder="请输入手机号" value={tel} name="tel" onChange={this.handChange.bind(this)} />
          <Input placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handChange.bind(this)} />
          <Button type="primary" onClick={this.loginClick.bind(this)}>登录</Button>
          {
            flag && <Button type="primary" onClick={() => { this.props.history.push("/register") }}>注册</Button>
          }
        </div>
      </div>
    )
  }
  handChange(e) {
    let name = e.target.name;
    this.setState({
      [name]: e.target.value
    })
  }
  async loginClick() {
    let { tel, pwd } = this.state;
    let res = await axios.post("/login", { tel, pwd });
    if (res.data.code === 1) {
      console.log(res.data.msg);
      localStorage.setItem("token", res.data.token);
      this.props.history.push("/home");
    } else {
      console.log(res.data.msg);
      this.setState({
        flag: true
      })
    }
  }
}
