// 六组/郭勇良/2.12作业/qx-react/src/views/Login/Login.js
import React, { Component } from 'react'
import axios from "axios"
export default class Login extends Component {
    state = {
        name:'',
        pwd:''
    }
    render() {
        let {name,pwd} = this.state; 
        return (
            <div className="login">
                 <p>
                     
                    <input placeholder="请输入用户名" value={name} name="name" onChange={this.handleChange.bind(this)} />
                </p>
                <p>
                    <input type="password" placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handleChange.bind(this)} />
                </p>
                <button onClick={this.handleSubmit.bind(this)}>登录</button>
            </div>
        )
    }
    handleChange(e){
        let name = e.target.name;
        this.setState({
            [name]:e.target.value
        })
    }
   async handleSubmit(){
        let {name,pwd} = this.state;
        let res =await  axios.post('/login',{
            name,pwd
        });
        if(res.data.code==1){
            window.localStorage.name=name;
            window.localStorage.uid=res.data.uid;
            window.localStorage.token=res.data.token;
            this.props.history.push("/index")
        }else if(res.data.code==3){
            this.props.history.push("/registry")
        }
    }
    
}

// 七组/薛莹/2.5作业/语雀前端/src/views/login/login.vue
<template>
  <div class="login">
    <p>
      <input type="text" v-model="name" placeholder="请输入用户名"/>
    </p>
    <p>
      <input type="password" v-model="pwd" placeholder="请输入密码"/>
    </p>
    <p>
      <button @click="islogin">登录</button>
      <button v-if="isshow" @click="gotore">注册</button>
    </p>
  </div>
</template>

<script>
import {login} from "@/api/api.js";
export default {
  data() {
    return {
      name: "",
      pwd: "",
      isshow: false
    };
  },
  methods: {
    async islogin() {
      let { name, pwd } = this;
      let res = await login( { name, pwd });
        console.log(this)
      if (res.data.code == 1) {
        window.localStorage.uid=res.data.uid;
        window.localStorage.token=res.data.token;
        window.localStorage.name=this.name;
        this.$router.push("/index");
      } else if (res.data.code == 2) {
        this.isshow = true;
        console.log(res.data);
      }
    },
    gotore() {
      this.$router.push("/registry");
    }
  }
};
</script>

<style scoped lang="scss">
.registry {
  width: 100%;
  height: 100%;
}
p {
  width: 100%;
  height: 50px;
  text-align: center;
  &:nth-child(1) {
    margin-top: 200px;
  }
}
</style>
