// 三组/刘枭飞/2.3router/src/views/Login/Login.vue
<template>
  <div>
    <el-input v-model="name" placeholder="请输入名字"></el-input>
    <el-input placeholder="请输入密码" v-model="pwd" show-password></el-input>
 <el-button type="primary" @click="dl">登陆</el-button>
   <a href="/zc">注册</a>
  </div>
</template>

<script>

import axios from "../../utils/httpAxios"
export default {
  data() {
    return {
      name:"",
      pwd:""
    }
  },
  methods:{
   async dl(){
     let {name,pwd} = this
     let res = await axios.post("/api/login",{name,pwd})
     console.log(res)
     if(res.data.code==1){
        window.localStorage.token = res.data.token;
        window.localStorage.uid = res.data.uid;
       this.$router.push("/home")
     }else{
       alert(res.data.msg)
     }
    }
  }
}
</script>

<style>

</style>

// 六组/郭勇良/2.14作业/tab-react/src/views/Login/Login.jsx
import React, { Component } from 'react'
import axios from "axios"
export default class Login extends Component {
    state = {
        name:'',
        pwd:''
    }
    render() {
        let {name,pwd} = this.state; 
        return (
            <div className="login">
                 <p>
                     
                    <input placeholder="请输入用户名" value={name} name="name" onChange={this.handleChange.bind(this)} />
                </p>
                <p>
                    <input type="password" placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handleChange.bind(this)} />
                </p>
                <button onClick={this.handleSubmit.bind(this)}>登录</button>
            </div>
        )
    }
    handleChange(e){
        let name = e.target.name;
        this.setState({
            [name]:e.target.value
        })
    }
   async handleSubmit(){
        let {name,pwd} = this.state;
        let res =await  axios.post('/login',{
            name,pwd
        });
        if(res.data.code==1){
            window.localStorage.name=name;
            window.localStorage.uid=res.data.uid;
            window.localStorage.token=res.data.token;
            this.props.history.push("/home")
        }else if(res.data.code==2){
            this.props.history.push("/registry")
        }
    }
    
}
