// 七组/赵春荣/2.4作业/语雀前端/src/views/login/login.vue
<template>
  <div class='login'>
    <el-input v-model="name" placeholder="请输入内容" class="input"></el-input>
    <br/>
    <el-input placeholder="请输入密码" v-model="pwd" show-password class="input"></el-input>
     <el-button type="primary" @click='fn'>登陆</el-button>
       <el-button type="danger" plain v-if='show' @click='gotoregistry'>注册</el-button>
    </div>
</template>
<script>
import axios from "axios"

export default {
  data(){
    return{
      name:'',
      pwd:'',
      show:false
    }
  },
  methods: {
    fn(){
      const {name,pwd,show}=this; 
    axios.post('/login',{
      name,pwd
    }).then(res=>{
       console.log(res.data)
       if(res.data.code===1){
         alert('登陆成功')
          window.localStorage.token=res.data.token;
         window.localStorage.id=res.data.uid
         this.$router.push('/home/list/file')
        
       }else if(res.data.code===3){
          this.show=true;
         alert('该用户不存在 请注册');
       }
     })
    },
    gotoregistry(){
      this.$router.push('/registry')
    }
  },
}
</script>
<style scoped>
  .login{
    width:100%;
    height:300px;
    border:1px solid #ccc;
    margin:60 auto;
  }
  .login .input{
   margin:20px;
  }
</style>

// 六组/郭勇良/2.14作业/tab-react/src/views/Login/Login.jsx
import React, { Component } from 'react'
import axios from "axios"
export default class Login extends Component {
    state = {
        name:'',
        pwd:''
    }
    render() {
        let {name,pwd} = this.state; 
        return (
            <div className="login">
                 <p>
                     
                    <input placeholder="请输入用户名" value={name} name="name" onChange={this.handleChange.bind(this)} />
                </p>
                <p>
                    <input type="password" placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handleChange.bind(this)} />
                </p>
                <button onClick={this.handleSubmit.bind(this)}>登录</button>
            </div>
        )
    }
    handleChange(e){
        let name = e.target.name;
        this.setState({
            [name]:e.target.value
        })
    }
   async handleSubmit(){
        let {name,pwd} = this.state;
        let res =await  axios.post('/login',{
            name,pwd
        });
        if(res.data.code==1){
            window.localStorage.name=name;
            window.localStorage.uid=res.data.uid;
            window.localStorage.token=res.data.token;
            this.props.history.push("/home")
        }else if(res.data.code==2){
            this.props.history.push("/registry")
        }
    }
    
}
