// 二组/刘洋/2.6/app/src/views/register/register.vue
<template>
  <div class="register">
      <el-input v-model="name" placeholder="请输入用户名"></el-input>
      <el-input v-model="pwd" placeholder="请输入密码"></el-input>
      <el-button @click="register">注册</el-button>
  </div>
</template>

<script>
import httpAxios from '../../utils/request'
export default {
 data() {
        return {
            name:"",
            pwd:""
        }
    },
    methods:{
        async register(){
            let {name,pwd}=this
            let res=await httpAxios.post("/api/register" ,{name,pwd})
            if(res.data.code==1){
                this.$router.push("/login")
            }else{
                alert(res.data.msg);
            }
        }
    }
}
</script>

<style>

</style>

// 三组/叶子文/2.11作业/react-2.11/src/views/Register/Register.js
import React, { Component } from 'react'
import axios from 'axios'

export default class componentName extends Component {
  state = {
    user: "",
    pwd: ""
  }
  render() {
    let { user, pwd } = this.state
    return (
      <div className="register">
        <div>
          <input type="text" value={user} name="user" onChange={this.handChange.bind(this)} />
          <input type="text" value={pwd} name="pwd" onChange={this.handChange.bind(this)} />
          <span onClick={this.registerClick.bind(this)}>注册</span>
        </div>
      </div>
    )
  }
  handChange(e) {
    let name = e.target.name;
    this.setState({
      [name]: e.target.value
    })
  }
  async registerClick() {
    let { user, pwd } = this.state
    let res = await axios.post("/register", { user, pwd });
    if (res.data.code === 1) {
      console.log("注册成功")
      this.props.history.push("/login")
    } else {
      console.log(res.data.msg)
    }
  }
}
