// 一组/张贾敏11/vueapp2.3/src/views/registry/registry.vue
<template>
  <div>
    <h1>注册页面</h1>
     <div>
       <el-input v-model="name" placeholder="请输入用户名"></el-input>
     </div>
       <div>
      <el-input placeholder="请输入密码" v-model="pwd" show-password class="el-input"></el-input>
    </div>
     <div>
    <el-button type="primary" @click="registry">注册</el-button>
    </div>
    </div>
</template>

<script>
import axios from "axios"
export default {
  data() {
      return {
        name:'',
        pwd: ''
      }
    },
    methods:{
     async registry(){
        let {name,pwd}=this;

        let res=await axios.post("/api/registry",{name,pwd})
        console.log(res,"111111111111")
        if(res.data.code===1){
          this.$router.push("/login")
        }

      }
    }
}
</script>

<style>

</style>

// 六组/郭勇良/2.13作业/tab-react/src/views/Registry/Registry.jsx
import React, { Component } from 'react'
import axios from "axios"
export default class Login extends Component {
    state = {
        name: '',
        pwd: ''
    }
    render() {
        let { name, pwd } = this.state;
        return (
            <div className="registry">
                <p>
                    <input placeholder="请输入用户名" value={name} name="name" onChange={this.handleChange.bind(this)} />
                </p>
                <p>
                    <input type="password" placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handleChange.bind(this)} />
                </p>

                <button onClick={this.handleSubmit.bind(this)}>注册</button>
            </div>
        )
    }
    handleChange(e) {
        let name = e.target.name;
        this.setState({
            [name]: e.target.value
        })
    }
    async handleSubmit() {
        let { name, pwd } = this.state;
        let res = await axios.post('/registry', {
            name, pwd
        });
        if (res.data.code == 1) {
            this.props.history.go(-1)
        } else if (res.data.code == 2) {
            this.props.history.push("/registry")
        }
    }

}
