// 七组/薛莹/2.3作业/语雀前端/src/views/registry/registry.vue
<template>
  <div class="login">
      <p>
          <input type="text" v-model="name">
      </p>
      <p>
          <input type="password" v-model="pwd">
      </p>
      <button @click="isregistry">注册</button>
  </div>
</template>

<script>
import axios from "axios"
export default {
    data(){
        return {
            name:"",
            pwd:""
        }
    },
    methods:{
        async isregistry(){
            let {name,pwd,isshow}=this;
            let res=await axios.post("/api/registry",{name,pwd});

            if(res.data.code==1){
                this.$router.push("/login")
            }else if(res.data.code==2){
                console.log(res.data)
            }
        }
    }
}
</script>

<style>

</style>

// 六组/郭勇良/2.11作业/qx-react/src/components/Registry/Registry.jsx
import React, { Component } from 'react'
import Axios from 'axios';

export default class Login extends Component {
    state={
        name:"",
        pwd:""
    }
    render() {
        let {name,pwd}=this.state
        return (
            <div>
              <p>用户名：<input type="text" value={name} name='name' onChange={this.handleChange.bind(this)}/></p> 
              <p>密码：<input type="password" value={pwd} name='pwd' onChange={this.handleChange.bind(this)}/></p>
              <p><button onClick={this.Submit.bind(this)}>注册</button></p>   
            </div>
        )
    }
    handleChange(e){
        let name=e.target.name
        this.setState({
            [name]:e.target.value
        })
    }
    async Submit(){
        let {name,pwd}=this.state
        let res=await Axios.post("/registry",{name,pwd})
      if(res.data.code===1){
        alert("注册成功")
        this.props.history.push("/login")
      }
        
    }
}
