// 二组/刘洋/2.6/app/src/views/register/register.vue
<template>
  <div class="register">
      <el-input v-model="name" placeholder="请输入用户名"></el-input>
      <el-input v-model="pwd" placeholder="请输入密码"></el-input>
      <el-button @click="register">注册</el-button>
  </div>
</template>

<script>
import httpAxios from '../../utils/request'
export default {
 data() {
        return {
            name:"",
            pwd:""
        }
    },
    methods:{
        async register(){
            let {name,pwd}=this
            let res=await httpAxios.post("/api/register" ,{name,pwd})
            if(res.data.code==1){
                this.$router.push("/login")
            }else{
                alert(res.data.msg);
            }
        }
    }
}
</script>

<style>

</style>

// 三组/叶子文/2.13作业/react-2.12/src/views/Register/Register.js
import React, { Component } from 'react'
import { Input, Button } from 'antd'
import axios from 'axios'

export default class Register extends Component {
  state = {
    tel: "",
    pwd: ""
  }
  render() {
    let { tel, pwd } = this.state;
    return (
      <div className="register">
        <div className="form">
          <Input placeholder="请输入手机号" value={tel} name="tel" onChange={this.handChange.bind(this)} />
          <Input placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handChange.bind(this)} />
          <Button type="primary" onClick={this.registerClick.bind(this)}>注册</Button>
        </div>
      </div>
    )
  }
  handChange(e) {
    let name = e.target.name;
    this.setState({
      [name]: e.target.value
    })
  }
  async registerClick() {
    let { tel, pwd } = this.state;
    let res = await axios.post("/register", { tel, pwd });
    if (res.data.code === 1) {
      console.log(res.data.msg);
      this.props.history.push("/login");
    } else {
      console.log(res.data.msg);
    }
  }
}
