// 六组/胡瑞斌1/2.6作业/111/src/views/register.vue
<template>
  <div class="about">
    <input placeholder="请输入用户名" v-model="name"><br>
    <input placeholder="请输入密码" v-model="pwd"><br>
    <button @click="fn">注册</button>
  </div>
</template>

<script>
import {register} from '@/api/api.js'
export default {
  data(){
    return {
      name:'',
      pwd:''
    }
  },
  methods:{
    async fn(){
      let {name,pwd} = this
      console.log(name,pwd);
      let res = await register({name,pwd})
      console.log(res);
      if(res.data.code==1){
        this.$router.go(-1)
      }else {
        this.$message(res.data.mes)
      }
    }
  }
}
</script>

<style scoped>
  input{
    width: 200px;
    height: 30px;
    margin-top: 20px;
  }
</style>

// 三组/叶子文/2.13作业/react-2.12/src/views/Register/Register.js
import React, { Component } from 'react'
import { Input, Button } from 'antd'
import axios from 'axios'

export default class Register extends Component {
  state = {
    tel: "",
    pwd: ""
  }
  render() {
    let { tel, pwd } = this.state;
    return (
      <div className="register">
        <div className="form">
          <Input placeholder="请输入手机号" value={tel} name="tel" onChange={this.handChange.bind(this)} />
          <Input placeholder="请输入密码" value={pwd} name="pwd" onChange={this.handChange.bind(this)} />
          <Button type="primary" onClick={this.registerClick.bind(this)}>注册</Button>
        </div>
      </div>
    )
  }
  handChange(e) {
    let name = e.target.name;
    this.setState({
      [name]: e.target.value
    })
  }
  async registerClick() {
    let { tel, pwd } = this.state;
    let res = await axios.post("/register", { tel, pwd });
    if (res.data.code === 1) {
      console.log(res.data.msg);
      this.props.history.push("/login");
    } else {
      console.log(res.data.msg);
    }
  }
}
