// 三组/刘枭飞/2.3router/src/views/Login/Login.vue
<template>
  <div>
    <el-input v-model="name" placeholder="请输入名字"></el-input>
    <el-input placeholder="请输入密码" v-model="pwd" show-password></el-input>
 <el-button type="primary" @click="dl">登陆</el-button>
   <a href="/zc">注册</a>
  </div>
</template>

<script>

import axios from "../../utils/httpAxios"
export default {
  data() {
    return {
      name:"",
      pwd:""
    }
  },
  methods:{
   async dl(){
     let {name,pwd} = this
     let res = await axios.post("/api/login",{name,pwd})
     console.log(res)
     if(res.data.code==1){
        window.localStorage.token = res.data.token;
        window.localStorage.uid = res.data.uid;
       this.$router.push("/home")
     }else{
       alert(res.data.msg)
     }
    }
  }
}
</script>

<style>

</style>

// 二组/刘洋/2.11/react-app/src/views/login/login.js
import React, { Component } from 'react'
import httpAxios from '../../utils/request'
export default class login extends Component {
    constructor(){
        super()
        this.state={
            name:"",
            pwd:""
        }
    }
    changeVal(e){
        let name=e.target.name
        this.setState({
            [name]:e.target.value
        })
        
    }
   async login(){
        let {name,pwd}=this.state
       let res=await httpAxios.post("/api/login",{name,pwd})
       console.log(res.data)
       if(res.data.code===1){
           console.log(this.props.history)
           localStorage.name=res.data.data.name
           localStorage.token=res.data.data.token
           localStorage.statu=res.data.data.statu
           this.props.history.push("/index")
       }else{
           alert(res.data.msg)
       }
    }
    toregister(){
        this.props.history.push("/register")
    }
    render() {
        let {name,pwd}=this.state
        return (
            <div className="login">
               <p>用户名:<input value={name} name="name" onChange={(e)=>{this.changeVal(e)}}></input></p>
               <p>密码:<input value={pwd} name="pwd"  onChange={(e)=>{this.changeVal(e)}}></input></p>
               <button onClick={()=>{this.login()}}>登陆</button>
               <button onClick={()=>{this.toregister()}}>注册</button>
            </div>
        )
    }
}
