// 二组/刘洋/2.6/app/src/views/login/login.vue
<template>
  <div class="login">
      <el-input v-model="name" placeholder="请输入用户名"></el-input>
        <el-input v-model="pwd" placeholder="请输入密码"></el-input>
         <el-button @click="tologin">登陆</el-button>
          <el-button @click="toregister">注册</el-button>
  </div>
</template>

<script>
import httpAxios from '../../utils/request'
export default {
        data() {
            return {
                name:"",
                pwd:""
            }
        },
    methods:{
       async tologin(){
           let {name,pwd}=this
          let res=await  httpAxios.post("/api/login",{name,pwd})
          console.log(res)
          if(res.data.code==1){
              this.$router.push("/index")
              localStorage.token=res.data.token
              localStorage.uid=res.data.uid
              localStorage.name=res.data.name
          }else{
              alert(res.data.msg);
          }
        },
        async toregister(){
             this.$router.push("/register")
        }
    }
}
</script>

<style>

</style>

// 二组/刘洋/2.11/react-app/src/views/login/login.js
import React, { Component } from 'react'
import httpAxios from '../../utils/request'
export default class login extends Component {
    constructor(){
        super()
        this.state={
            name:"",
            pwd:""
        }
    }
    changeVal(e){
        let name=e.target.name
        this.setState({
            [name]:e.target.value
        })
        
    }
   async login(){
        let {name,pwd}=this.state
       let res=await httpAxios.post("/api/login",{name,pwd})
       console.log(res.data)
       if(res.data.code===1){
           console.log(this.props.history)
           localStorage.name=res.data.data.name
           localStorage.token=res.data.data.token
           localStorage.statu=res.data.data.statu
           this.props.history.push("/index")
       }else{
           alert(res.data.msg)
       }
    }
    toregister(){
        this.props.history.push("/register")
    }
    render() {
        let {name,pwd}=this.state
        return (
            <div className="login">
               <p>用户名:<input value={name} name="name" onChange={(e)=>{this.changeVal(e)}}></input></p>
               <p>密码:<input value={pwd} name="pwd"  onChange={(e)=>{this.changeVal(e)}}></input></p>
               <button onClick={()=>{this.login()}}>登陆</button>
               <button onClick={()=>{this.toregister()}}>注册</button>
            </div>
        )
    }
}
